AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  sdlv4Function:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: sdlv4App
      Handler: lambda.handler
      Runtime: ruby2.5
      #Policies:
      #  - DynamoDBCrudPolicy:
      #      TableName: !Ref FeedbackTable
      CodeUri: "./"
      MemorySize: 512
      Timeout: 30
      Events:
        sdlv4Api:
            Type: Api
            Properties:
                Path: /
                Method: ANY
                RestApiId: !Ref sdlv4API
  sdlv4API:
    Type: AWS::Serverless::Api
    Properties:
      Name: sdlv4API
      StageName: Prod
      DefinitionBody:
        swagger: '2.0'
        basePath: '/Prod'
        info:
          title: !Ref AWS::StackName
        paths:
          /{proxy+}:
            x-amazon-apigateway-any-method:
              responses: {}
              x-amazon-apigateway-integration:
                uri:
                  !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${sdlv4Function.Arn}/invocations'
                passthroughBehavior: "when_no_match"
                httpMethod: POST
                type: "aws_proxy"
          /:
            get:
              responses: {}
              x-amazon-apigateway-integration:
                uri:
                  !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${sdlv4Function.Arn}/invocations'
                passthroughBehavior: "when_no_match"
                httpMethod: POST
                type: "aws_proxy"
  ConfigLambdaPermission:
    Type: "AWS::Lambda::Permission"
    DependsOn:
    - sdlv4Function
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref sdlv4Function
      Principal: apigateway.amazonaws.com
  #CloudFormationTrustRole:
   # Description: Creating service role in IAM for AWS CloudFormation
   # Type: AWS::IAM::Role
   # Properties:
   #   RoleName: !Sub "sdlv4-cloudformation-role"
   #   AssumeRolePolicyDocument:
   #     Statement:
   #       - Effect: Allow
   #         Principal:
   #           Service: [cloudformation.amazonaws.com]
   #         Action: sts:AssumeRole
   #   Path: /
  #CloudFormationRolePolicy:
   # Type: AWS::IAM::Policy
   # DependsOn: CloudFormationTrustRole
   # Description: Setting IAM policy for the service role for AWS CloudFormation
   # Properties:
    #  PolicyName: CloudFormationRolePolicy
    #  PolicyDocument:
     #   Statement:
     #     - Action: ["s3:GetObject", "s3:GetObjectVersion", "s3:GetBucketVersioning"]
     #       Resource: "*"
     #       Effect: Allow
     #     - Action: ["lambda:*"]
     #       Resource: !Sub "arn:aws:lambda:us-east-1::function:*"
     #       Effect: Allow
     #     - Action: ["apigateway:*"]
     #       Resource: !Sub "arn:aws:apigateway:us-east-1::*"
     #       Effect: Allow
     #     - Action: ["iam:GetRole", "iam:CreateRole", "iam:DeleteRole"]
     #       Resource: !Sub "arn:aws:iam::role/sdlv4-*"
     #       Effect: Allow
     #     - Action: ["iam:AttachRolePolicy", "iam:DetachRolePolicy"]
     #       Resource: !Sub "arn:aws:iam::role/sdlv4-*"
     #       Effect: Allow
     #     - Action: ["iam:PassRole"]
     #       Resource: ["*"]
     #       Effect: Allow
     #     - Action: ["cloudformation:CreateChangeSet"]
     #       Resource: !Sub "arn:aws:cloudformation::aws:tranform/serverless-2016-10-31"
     #       Effect: Allow
     # Roles: [!Ref CloudFormationTrustRole]  
            
  
  
  #FeedbackTable:
  #  Type: AWS::Serverless::SimpleTable
  #  Properties:
  #    TableName: FeedbackServerlessLastLambdaTable
  #    PrimaryKey: 
  #      Name: id
  #     Type: String
  #    ProvisionedThroughput: 
  #      ReadCapacityUnits: 5
  #      WriteCapacityUnits: 5
Outputs:
  sdlv4AppUrl:
    Description: App endpoint URL
    Value: !Sub "https://${sdlv4API}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  #CloudformationDeployRole:
   # Description: "Role for cloudformation to deploy with."
   # Value: !GetAtt CloudFormationTrustRole.Arn
